import { describe, it, expect } from "vitest";
import { createRace, advanceRace, advanceRaceLap, simulateRace } from "../src/simulation/race/engine";
import { defaultCommandConfiguration, commandLapEffects, projectedFuelGrams, validateCommandState, type CommandState } from "../src/simulation/race/commands/model";
import { chooseAiCommands } from "../src/simulation/race/commands/policy";
import { requestPitStop } from "../src/simulation/race/pits/model";
import { pitInput } from "./helpers/pits";
import fixture from "./fixtures/race-v4.json";
import { battleRate } from "./helpers/commands";
import type { RaceSimulationInput, RaceSimulationState } from "../src/simulation/race/types";
export function commandInput(count = 1): RaceSimulationInput { return {...pitInput(42,count,75), initialFuelKg:130, commands:defaultCommandConfiguration()}; }
export function modes(s: RaceSimulationState, values: Partial<CommandState>, index = 0): RaceSimulationState { return {...s,entrants:s.entrants.map((e,n)=>n === index ? {...e,commands:{...e.commands!,...values}}:e)}; }
function stint(values: Partial<CommandState>, laps=5) { return advanceRace(modes(createRace(commandInput()),values),laps).entrants[0]; }
describe("v5 command mechanics",()=>{
 it("DRS plus OVERTAKE improves passing without guarantee",()=>{const neutral=battleRate("NEUTRAL"),boost=battleRate("OVERTAKE");expect(boost).toBeGreaterThan(neutral);expect(boost).toBeLessThan(200);});
 it("defending deployment reduces passing relative to harvesting",()=>expect(battleRate("OVERTAKE","DEPLOY")).toBeLessThan(battleRate("OVERTAKE","HARVEST")));

 it("preserves captured v4 output",()=>expect(simulateRace(fixture.state.input as RaceSimulationInput)).toEqual(fixture));
 it("starts defaults and snapshots profiles",()=>{const i=commandInput();const s=createRace(i);i.commands!.pace.ATTACK.lapTimeDeltaMs=0;expect(s.simulationVersion).toBe(5);expect(s.entrants[0].commands).toEqual({paceMode:"STANDARD",fuelMode:"BALANCED",ersMode:"NEUTRAL",ersCharge:700,commandRevision:0});expect(s.input.commands!.pace.ATTACK.lapTimeDeltaMs).toBe(-550);});
 it("pace trades immediate performance for tyre wear and temperature",()=>{const c=stint({paceMode:"CONSERVE"}),s=stint({}),a=stint({paceMode:"ATTACK"});expect(a.elapsedTimeMs).toBeLessThan(s.elapsedTimeMs);expect(s.elapsedTimeMs).toBeLessThan(c.elapsedTimeMs);expect(a.stint!.tyre.wearPermille).toBeGreaterThan(s.stint!.tyre.wearPermille);expect(c.stint!.tyre.wearPermille).toBeLessThan(s.stint!.tyre.wearPermille);expect(a.stint!.tyre.temperatureMilliC).toBeGreaterThan(c.stint!.tyre.temperatureMilliC);});
 it("fuel trades pace and burn over multiple laps",()=>{const c=stint({fuelMode:"CONSERVE"}),b=stint({}),p=stint({fuelMode:"PUSH"});expect(p.elapsedTimeMs).toBeLessThan(b.elapsedTimeMs);expect(b.elapsedTimeMs).toBeLessThan(c.elapsedTimeMs);expect(p.fuelMassKg).toBeLessThan(b.fuelMassKg);expect(b.fuelMassKg).toBeLessThan(c.fuelMassKg);});
 it.each(["HARVEST","NEUTRAL","DEPLOY","OVERTAKE"] as const)("ERS %s is bounded for full race",ersMode=>{const e=stint({ersMode},75);expect(e.commands!.ersCharge).toBeGreaterThanOrEqual(0);expect(e.commands!.ersCharge).toBeLessThanOrEqual(1000);});
 it("deployment strength and consumption order",()=>{const h=stint({ersMode:"HARVEST"},1),n=stint({},1),d=stint({ersMode:"DEPLOY"},1),o=stint({ersMode:"OVERTAKE"},1);expect(h.commands!.ersCharge).toBeGreaterThan(n.commands!.ersCharge);expect(d.commands!.ersCharge).toBeLessThan(n.commands!.ersCharge);expect(o.commands!.ersCharge).toBeLessThan(d.commands!.ersCharge);expect(o.lastLapTimeMs).toBeLessThan(d.lastLapTimeMs!);expect(d.lastLapTimeMs).toBeLessThan(n.lastLapTimeMs!);});
 it("empty battery has no free deployment benefit",()=>{const s=modes(createRace(commandInput()),{ersCharge:0,ersMode:"OVERTAKE"});expect(commandLapEffects(s.entrants[0],1.6,s.input.commands!,false).deltaMs).toBe(0);});
 it("combined aggressive stint costs all resources",()=>{const a=stint({paceMode:"ATTACK",fuelMode:"PUSH",ersMode:"OVERTAKE"}),c=stint({paceMode:"CONSERVE",fuelMode:"CONSERVE",ersMode:"HARVEST"});expect(a.elapsedTimeMs).toBeLessThan(c.elapsedTimeMs);expect(a.fuelMassKg).toBeLessThan(c.fuelMassKg);expect(a.commands!.ersCharge).toBeLessThan(c.commands!.ersCharge);expect(a.stint!.tyre.wearPermille).toBeGreaterThan(c.stint!.tyre.wearPermille);});
 it("exhaustion adds severe penalty and never negative fuel",()=>{const i=commandInput();const s=createRace({...i,initialFuelKg:0.1});const next=advanceRaceLap(s);expect(next.entrants[0].fuelMassKg).toBe(0);expect(next.entrants[0].lastLapTimeMs).toBeGreaterThan(200000);});
 it("fuel deficit can be recovered by conserving",()=>{let s=createRace({...commandInput(),totalLaps:20,initialFuelKg:32});s=advanceRace(modes(s,{fuelMode:"PUSH"}),5);expect(projectedFuelGrams(s,s.entrants[0])).toBeLessThan(0);s=modes(s,{fuelMode:"CONSERVE"});expect(projectedFuelGrams(s,s.entrants[0])).toBeGreaterThan(0);expect(advanceRace(s,20).entrants[0].fuelMassKg).toBeGreaterThan(0);});
 it("pit preserves commands and resources, suppressing deployment",()=>{let s=modes(createRace(commandInput()),{paceMode:"ATTACK",fuelMode:"PUSH",ersMode:"OVERTAKE"});s=requestPitStop(s,s.entrants[0].entrantId,"HARD");const e=advanceRaceLap(s).entrants[0];expect(e.commands).toMatchObject({paceMode:"ATTACK",fuelMode:"PUSH",ersMode:"OVERTAKE",ersCharge:760});expect(e.fuelMassKg).toBeLessThan(s.entrants[0].fuelMassKg);expect(e.stint!.tyre.ageLaps).toBe(0);});
 it("exact resume with command changes, pits and AI",()=>{let s=advanceRace(createRace(commandInput(4)),10);s=modes(s,{paceMode:"ATTACK",fuelMode:"PUSH",ersMode:"OVERTAKE"});s=advanceRace(s,5);const finish=(x:RaceSimulationState)=>advanceRace(requestPitStop(modes(x,{paceMode:"CONSERVE",fuelMode:"CONSERVE",ersMode:"HARVEST"}),x.entrants[0].entrantId,"HARD"),75);expect(finish(JSON.parse(JSON.stringify(s)))).toEqual(finish(s));});
 it("AI harvests low charge and conserves deficit without overriding player",()=>{const i=commandInput(2);const s=modes(createRace({...i,initialFuelKg:10,entrants:i.entrants.map((e,n)=>({...e,strategyController:n ? "DEVELOPMENT_AI":"PLAYER"}))}),{paceMode:"ATTACK"});const low={...s,entrants:s.entrants.map(e=>({...e,commands:{...e.commands!,ersCharge:0}}))};const n=chooseAiCommands(low);expect(n.entrants[0].commands!.paceMode).toBe("ATTACK");expect(n.entrants[1].commands).toMatchObject({fuelMode:"CONSERVE",ersMode:"HARVEST"});});
 it("commands consume no RNG",()=>{const s=createRace(commandInput());expect(advanceRaceLap(s).rngState).toBe(advanceRaceLap(modes(s,{paceMode:"ATTACK",fuelMode:"PUSH",ersMode:"OVERTAKE"})).rngState);});
 it.each([-1,1001,0.5])("rejects invalid energy %s",ersCharge=>expect(()=>validateCommandState({...createRace(commandInput()).entrants[0].commands!,ersCharge},defaultCommandConfiguration())).toThrow());
 it("20 cars x 75 laps stays lightweight",()=>{const i=commandInput(20);const start=performance.now();simulateRace({...i,entrants:i.entrants.map(e=>({...e,strategyController:"DEVELOPMENT_AI"}))});expect(performance.now()-start).toBeLessThan(2000);});
});

import { setDriverPaceMode, setDriverFuelMode, setDriverErsMode } from "../src/features/race/service";
import type { CareerRaceData, CareerRaceRepository } from "../src/game/domain/race-repository";
import { translate } from "../src/i18n/catalog";
function memoryRace() {
 const input=commandInput(4);
 let data: CareerRaceData={state:createRace({...input,entrants:input.entrants.map((e,n)=>({...e,strategyController:n<2?"PLAYER":"DEVELOPMENT_AI"}))}),eventId:"event",sessionId:"session",roster:[],labels:[],circuit:{lengthMeters:5200,defaultLapCount:75},progress:{career:{id:"career",name:"Test",sourceGameDatabaseId:"db",sourceGameDatabaseVersion:"1",sourceSeasonId:"season",playerTeamId:"pit-team-0",currentSeasonId:"season",currentDate:"2026-01-01",status:"ACTIVE",createdAt:"2026-01-01",updatedAt:"2026-01-01"},events:[{id:"event",careerId:"career",careerSeasonId:"season",careerCircuitId:"circuit",sourceCalendarEventId:null,round:1,name:"Race",startDate:"2026-01-01",endDate:"2026-01-01",status:"CURRENT",circuitName:"Circuit",weekend:{id:"weekend",careerId:"career",careerSeasonId:"season",careerCalendarEventId:"event",status:"ACTIVE",sessions:[{id:"session",careerId:"career",careerRaceWeekendId:"weekend",type:"RACE",order:5,status:"IN_PROGRESS",startedAtCareerDate:"2026-01-01",completedAtCareerDate:null}]}}]}};
 const repository:CareerRaceRepository={getRace:async()=>structuredClone(data),changeRace:async(_c,_e,change)=>{const next=change(structuredClone(data));data={...data,...next};}};
 return {repository,get:()=>data};
}
describe("offline command application boundary",()=>{
 it("permits both player cars, rejects both AI cars",async()=>{const m=memoryRace();for(let n=0;n<2;n++)await setDriverPaceMode(m.repository,"career","event",`pit-entrant-${n}`,0,0,"ATTACK");for(let n=2;n<4;n++)await expect(setDriverPaceMode(m.repository,"career","event",`pit-entrant-${n}`,0,0,"ATTACK")).rejects.toMatchObject({code:"INVALID_ACTION"});});
 it("checks actual Career team even if controller is forged",async()=>{const m=memoryRace();await m.repository.changeRace("career","event",d=>({state:{...d.state!,input:{...d.state!.input,entrants:d.state!.input.entrants.map(e=>({...e,strategyController:"PLAYER"}))}},labels:d.labels,progress:d.progress}));await expect(setDriverPaceMode(m.repository,"career","event","pit-entrant-2",0,0,"ATTACK")).rejects.toMatchObject({code:"INVALID_ACTION"});});
 it("commands take effect next lap, revision shared by all intents",async()=>{const m=memoryRace(),before=structuredClone(m.get().state!);await setDriverPaceMode(m.repository,"career","event","pit-entrant-0",0,0,"ATTACK");await setDriverFuelMode(m.repository,"career","event","pit-entrant-0",0,1,"PUSH");await setDriverErsMode(m.repository,"career","event","pit-entrant-0",0,2,"OVERTAKE");const s=m.get().state!;expect(s.lap).toBe(0);expect(s.rngState).toBe(before.rngState);expect(s.entrants[0].stint).toEqual(before.entrants[0].stint);expect(s.entrants[0].fuelMassKg).toBe(before.entrants[0].fuelMassKg);expect(advanceRaceLap(s).entrants.find(e=>e.entrantId==="pit-entrant-0")!.commands!.ersCharge).toBe(460);await expect(setDriverPaceMode(m.repository,"career","event","pit-entrant-0",0,0,"STANDARD")).rejects.toMatchObject({code:"STALE"});});
 it("translations are presentation-only",()=>{const s=createRace(commandInput()),before=structuredClone(s);expect(translate("en","command.ATTACK")).toBe("Attack");expect(translate("zh-TW","command.ATTACK")).toBe("進攻");expect(s).toEqual(before);});
 it("AI cycles battery and never remains in impossible deployment",()=>{const i=commandInput(2);let s=createRace({...i,parameters:{...i.parameters,gridOffsetMs:100},entrants:i.entrants.map(e=>({...e,strategyController:"DEVELOPMENT_AI"}))});const seen=new Set<string>();for(let lap=0;lap<30;lap++){s=advanceRaceLap(s);for(const e of s.entrants){seen.add(e.commands!.ersMode);expect(e.commands!.paceMode).not.toBe("ATTACK");expect(e.commands!.ersCharge).toBeGreaterThanOrEqual(0);}}expect(seen.has("HARVEST")).toBe(true);expect(seen.has("OVERTAKE")||seen.has("DEPLOY")).toBe(true);});
 it("AI selected modes use exactly the player physics",()=>{const i=commandInput();const ai=createRace({...i,entrants:i.entrants.map(e=>({...e,strategyController:"DEVELOPMENT_AI"}))});const choice=chooseAiCommands(ai).entrants[0].commands!;const player=modes(createRace(i),choice);const a=advanceRaceLap(ai).entrants[0],p=advanceRaceLap(player).entrants[0];expect(a).toEqual(p);});
});
