import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { createRace, advanceRace, advanceRaceLap, simulateRace } from "../src/simulation/race/engine";
import { incidentInput, quietRace, neutralise, forceMechanical } from "./helpers/incidents";
import { weatherInput } from "./helpers/weather";
import { requestPitStop } from "../src/simulation/race/pits/model";
import { driverRiskPpm, mechanicalRiskPpm, effectivePitLaneLoss } from "../src/simulation/race/incidents/model";
import { createSeededRandom } from "../src/simulation/core/random";
import { tyreContributions } from "../src/simulation/race/tyres/model";
describe("v7 incidents and neutralisation", () => {
    it("v6 fixture remains byte-equivalent in value", () => expect(simulateRace(weatherInput(4))).toEqual(JSON.parse(readFileSync(new URL('./fixtures/race-v6.json', import.meta.url), 'utf8'))));
    it("snapshots independent reliability and v7 state", () => { const i = incidentInput(), s = createRace(i); i.entrants[0].reliability.control = 0; expect(s.input.entrants[0].reliability!.control).toBe(85); expect(s.simulationVersion).toBe(7); });
    it("quiet v7 exactly preserves base RNG before interactions diverge", () => { const s = quietRace(); const { incidents: _, ...input } = s.input; void _; const v6 = createRace(input); expect(advanceRace(s, 5).rngState).toBe(advanceRace(v6, 5).rngState); });
    it("consumes exactly six incident draws per grid slot, even during SC", () => { const s = neutralise(quietRace(), "SAFETY_CAR"), r = createSeededRandom(s.incidents!.rngState); for (let i = 0; i < 24; i++)
        r.next(); expect(advanceRaceLap(s).incidents!.rngState).toBe(r.getState()); });
    it("persistent mechanical loss adds 800ms with no instant repair", () => { const s = forceMechanical(quietRace(1)); const a = advanceRaceLap(s), b = advanceRaceLap(a); expect(a.entrants[0].incident!.mechanicalPenaltyMs).toBe(800); expect(b.entrants[0].incident!.mechanicalPenaltyMs).toBe(1600); expect(a.incidents!.events[0].kind).toBe("MECHANICAL_PROBLEM"); });
    it("mechanical retirement freezes resources and prohibits pits", () => { const s = advanceRaceLap(forceMechanical(quietRace(2), true)); const next = advanceRace(s, 5); for (const e of s.entrants) {
        const n = next.entrants.find(x => x.entrantId === e.entrantId)!;
        expect(n).toEqual(e);
        expect(() => requestPitStop(s, e.entrantId, "HARD")).toThrow();
    } expect(s.incidents!.mode).toBe("VSC"); });
    it.each(["VSC", "SAFETY_CAR"] as const)("%s resumes identically from serialized checkpoint", mode => { const s = advanceRaceLap(neutralise(quietRace(), mode)); expect(advanceRace(JSON.parse(JSON.stringify(s)), 1000)).toEqual(advanceRace(s, 1000)); });
    it.each(["VSC", "SAFETY_CAR"] as const)("%s prohibits overtakes and DRS, suppresses recursive incidents", mode => { const s = neutralise(forceMechanical(quietRace(), true), mode), next = advanceRaceLap(s); expect(next.entrants.map(e => e.entrantId)).toEqual(s.entrants.map(e => e.entrantId)); expect(next.entrants.every(e => !e.track!.drsEligible && !e.track!.attempted && e.track!.overtakesCompleted === 0)).toBe(true); expect(next.incidents!.events).toEqual([]); });
    it("VSC preserves gaps and SC compresses gradually", () => { let s = quietRace(); s = { ...s, entrants: s.entrants.map((e, i) => ({ ...e, elapsedTimeMs: i * 10000 })) }; const v = advanceRaceLap(neutralise(s, "VSC")), sc = advanceRaceLap(neutralise(s, "SAFETY_CAR")); expect(v.entrants[1].intervalToAheadMs).toBe(10000); expect(sc.entrants[1].intervalToAheadMs).toBe(6400); expect(sc.entrants[2].intervalToAheadMs).toBe(6400); });
    it("SC saves most fuel and wears tyres least", () => { const s = quietRace(1), g = advanceRaceLap(s).entrants[0], v = advanceRaceLap(neutralise(s, "VSC")).entrants[0], sc = advanceRaceLap(neutralise(s, "SAFETY_CAR")).entrants[0]; expect(sc.fuelMassKg).toBeGreaterThan(v.fuelMassKg); expect(v.fuelMassKg).toBeGreaterThan(g.fuelMassKg); expect(sc.stint!.tyre.wearPermille).toBeLessThan(v.stint!.tyre.wearPermille); expect(v.stint!.tyre.wearPermille).toBeLessThan(g.stint!.tyre.wearPermille); });
    it("SC suppresses player attack/ERS deployment without overwriting modes", () => { let s = quietRace(1); s = { ...s, entrants: s.entrants.map(e => ({ ...e, commands: { ...e.commands!, paceMode: "ATTACK", ersMode: "OVERTAKE" } })) }; const n = advanceRaceLap(neutralise(s, "SAFETY_CAR")); expect(n.entrants[0].commands!.paceMode).toBe("ATTACK"); expect(n.entrants[0].commands!.ersMode).toBe("OVERTAKE"); expect(n.entrants[0].commands!.ersCharge).toBeGreaterThan(s.entrants[0].commands!.ersCharge); expect(n.entrants[0].lastLapTimeMs).toBe(Math.round(s.input.circuit.baseLapTimeMs * 1.65)); });
    it("SC cooling increases restart cold penalty then recovers", () => { let s = quietRace(1); s = { ...s, entrants: s.entrants.map(e => ({ ...e, stint: { ...e.stint!, tyre: { ...e.stint!.tyre, temperatureMilliC: 90000 } } })) }; const end = advanceRace(neutralise(s, "SAFETY_CAR", 5), 5), tyre = end.entrants[0].stint!.tyre, p = s.input.tyres!.profiles[tyre.compound]; expect(tyre.temperatureMilliC).toBeLessThan(90000); const restart = advanceRace(end, 5).entrants[0].stint!.tyre; expect(restart.temperatureMilliC).toBeGreaterThan(tyre.temperatureMilliC); expect(tyreContributions(tyre, p).tyreTemperatureMs).toBeGreaterThanOrEqual(tyreContributions(restart, p).tyreTemperatureMs); });
    it("SC restart counts two green laps before DRS can return", () => { let s = advanceRaceLap(neutralise(quietRace(2), "SAFETY_CAR", 1)); expect(s.incidents!.mode).toBe("GREEN"); expect(s.incidents!.drsDelay).toBe(2); for (let i = 1; i >= 0; i--) {
        s = advanceRaceLap(s);
        expect(s.incidents!.drsDelay).toBe(i);
        expect(s.entrants.every(e => !e.track!.drsEligible)).toBe(true);
    } expect(advanceRaceLap(s).incidents!.drsDelay).toBe(0); });
    it.each(["VSC", "SAFETY_CAR"] as const)("%s stop uses unchanged service draw and reduced relative route loss", mode => { const s = quietRace(2), id = s.entrants[1].entrantId; const run = (x: typeof s) => advanceRaceLap(requestPitStop(x, id, "HARD")).entrants.find(e => e.entrantId === id)!; const g = run(s), n = run(neutralise(s, mode)); expect(n.pit!.stops[0].stationaryTimeMs).toBe(g.pit!.stops[0].stationaryTimeMs); expect(n.pit!.stops[0].pitLaneLossMs).toBe(effectivePitLaneLoss(neutralise(s, mode))); expect(n.pit!.stops[0].totalLossMs).toBeLessThan(g.pit!.stops[0].totalLossMs); expect(n.position).toBe(2); });
    it("AI adopts conservative modes during SC then returns to normal policy", () => { let s = quietRace(1); s = { ...s, input: { ...s.input, entrants: s.input.entrants.map(e => ({ ...e, strategyController: "DEVELOPMENT_AI" })) } }; const sc = advanceRaceLap(neutralise(s, "SAFETY_CAR", 1)); expect(sc.entrants[0].commands).toMatchObject({ paceMode: "CONSERVE", fuelMode: "CONSERVE", ersMode: "HARVEST" }); expect(advanceRaceLap(sc).entrants[0].commands!.paceMode).not.toBe("CONSERVE"); });
    it("controlled seeds cover lockup, spin, contact and minor/major outcomes", () => { const kinds = new Set<string>(), severities = new Set<string>(); for (let seed = 1; seed < 300; seed++) {
        const i = incidentInput(4, seed);
        i.incidents = { ...i.incidents, baseErrorPpm: 350000, maxErrorPpm: 1000000, majorPermille: 200, moderatePermille: 200 };
        i.parameters = { ...i.parameters, gridOffsetMs: 180 };
        const s = advanceRaceLap(createRace(i));
        for (const e of s.incidents!.events) {
            if (e.kind)
                kinds.add(e.kind);
            if (e.severity)
                severities.add(e.severity);
        }
    } expect([...kinds]).toEqual(expect.arrayContaining(["LOCK_UP", "SPIN", "CONTACT", "DRIVER_MISTAKE"])); expect(severities.size).toBe(3); });
    it("risk ordering is bounded across control, pace, wear, wet suitability and reliability", () => { const s = quietRace(1); const i = incidentInput(1), x = createRace(i), e = x.entrants[0], p = i.entrants[0]; expect(driverRiskPpm(x, e, { ...p, reliability: { ...p.reliability, control: 20 } })).toBeGreaterThan(driverRiskPpm(x, e, p)); expect(driverRiskPpm(x, { ...e, commands: { ...e.commands!, paceMode: "ATTACK" } }, p)).toBeGreaterThan(driverRiskPpm(x, e, p)); expect(driverRiskPpm({ ...x, weather: { ...x.weather!, trackWater: 800 } }, e, p)).toBeGreaterThan(driverRiskPpm(x, e, p)); expect(mechanicalRiskPpm(x, { ...p, reliability: { ...p.reliability, reliability: 0 } })).toBeGreaterThan(mechanicalRiskPpm(x, p)); expect(driverRiskPpm(s, s.entrants[0], s.input.entrants[0])).toBe(0); });
    it("20 cars × 75 laps remains deterministic and lightweight", () => { const i = incidentInput(20, 42, 75), start = performance.now(), a = simulateRace(i); expect(simulateRace(i)).toEqual(a); expect(a.state.status).toBe("FINISHED"); expect(performance.now() - start).toBeLessThan(3000); });
});
it("actual SC deployment with retirement resumes through restart exactly", () => { const i = incidentInput(4, 1); i.parameters = { ...i.parameters, gridOffsetMs: 180 }; i.incidents = { ...i.incidents, baseErrorPpm: 300000, maxErrorPpm: 1000000, majorPermille: 1000, moderatePermille: 0, scMajorPermille: 1000 }; const first = advanceRaceLap(createRace(i)); expect(first.incidents!.mode).toBe("SAFETY_CAR"); expect(first.incidents!.events.some(e => e.type === "RETIREMENT")).toBe(true); expect(first.entrants.every(e => !e.track!.drsEligible)).toBe(true); expect(advanceRace(JSON.parse(JSON.stringify(first)), 1000)).toEqual(advanceRace(createRace(i), 1000)); });
it("DRS actually returns on third green lap, and wet weather still blocks it", () => { let s = quietRace(2); s = { ...s, input: { ...s.input, interaction: { ...s.input.interaction!, drsActivationLap: 1 } }, entrants: s.entrants.map((e, i) => ({ ...e, elapsedTimeMs: i * 200, intervalToAheadMs: i * 200 })) }; const end = advanceRaceLap(neutralise(s, "SAFETY_CAR", 1)); const waiting = advanceRace(end, 2); expect(waiting.entrants.every(e => !e.track!.drsEligible)).toBe(true); expect(advanceRaceLap(waiting).entrants.some(e => e.track!.drsEligible)).toBe(true); const wet = { ...waiting, weather: { ...waiting.weather!, trackWater: 1000, drsState: "DRS_DISABLED_WET" as const } }; expect(advanceRaceLap(wet).entrants.every(e => !e.track!.drsEligible)).toBe(true); });
it("AI considers a worn-tyre SC pit opportunity through the same route cost", () => { let s = quietRace(1); s = { ...s, lap: 10, input: { ...s.input, entrants: s.input.entrants.map(e => ({ ...e, strategyController: "DEVELOPMENT_AI" })) }, entrants: s.entrants.map(e => ({ ...e, completedLaps: 10, stint: { ...e.stint!, tyre: { ...e.stint!.tyre, wearPermille: 770, ageLaps: 10 } } })) }; expect(advanceRaceLap(s).entrants[0].pit!.stops).toHaveLength(0); expect(advanceRaceLap(neutralise(s, "SAFETY_CAR")).entrants[0].pit!.stops).toHaveLength(1); });
it("incident delays lose positions without increasing overtaking statistics", () => { let found = false; for (let seed = 1; seed < 100 && !found; seed++) {
    const i = incidentInput(2, seed);
    i.parameters = { ...i.parameters, gridOffsetMs: 100 };
    i.interaction = { ...i.interaction!, minimumPaceAdvantageMs: 2000 };
    i.incidents = { ...i.incidents, baseErrorPpm: 200000, maxErrorPpm: 1000000, majorPermille: 0, moderatePermille: 0, vscMinorPermille: 0, baseMechanicalPpm: 0, conditionDeficitPpm: 0, distanceRiskPpm: 0 };
    const n = advanceRaceLap(createRace(i));
    if (n.incidents!.events.some(e => e.entrantIds.includes(i.entrants[0].entrantId)) && n.entrants[0].entrantId !== i.entrants[0].entrantId) {
        expect(n.entrants.every(e => e.track!.overtakesCompleted === 0)).toBe(true);
        found = true;
    }
} expect(found).toBe(true); });
it.each([-1, 101, NaN])("rejects reliability outside its bounded scale: %s", value => { const i = incidentInput(); i.entrants[0].reliability.reliability = value; expect(() => createRace(i)).toThrow(); });
it("rejects invalid severity probabilities and control duration", () => { const i = incidentInput(); i.incidents.majorPermille = 999; i.incidents.moderatePermille = 999; expect(() => createRace(i)).toThrow(); const s = quietRace(); expect(() => advanceRaceLap({ ...s, incidents: { ...s.incidents!, mode: "SAFETY_CAR", remainingLaps: 0 } })).toThrow(); });
it("finishers precede retirements and distance decides retired order", () => { let s = quietRace(3); s = { ...s, input: { ...s.input, incidents: { ...s.input.incidents!, conditionDeficitPpm: 1000000, mechanicalRetirementPermille: 1000, vscRetirementPermille: 0 }, entrants: s.input.entrants.map((e, i) => ({ ...e, reliability: { ...e.reliability!, reliability: i === 0 ? 0 : 100, powerUnitCondition: 100, gearboxCondition: 100 } })) } }; s = advanceRace(s, 2); const first = s.entrants.find(e => e.incident!.status === "RETIRED")!; s = { ...s, input: { ...s.input, entrants: s.input.entrants.map((e, i) => i === 1 ? { ...e, reliability: { ...e.reliability!, reliability: 0 } } : e) } }; const finished = advanceRace(s, 1000); expect(finished.entrants.map(e => e.incident!.status)).toEqual(["FINISHED", "RETIRED", "RETIRED"]); expect(finished.entrants[1].completedLaps).toBe(3); expect(finished.entrants[2].entrantId).toBe(first.entrantId); expect(finished.entrants[2].completedLaps).toBe(1); });
