import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it, vi } from 'vitest';
import { I18nProvider } from '../src/i18n/provider';
import { WeekendView } from '../src/features/career/progression-views';
import { QualifyingSummary, QualifyingTower } from '../src/features/qualifying/components';
import { qualifyingView } from '../src/features/qualifying/view-model';
import { simulateQualifyingSession } from '../src/features/qualifying/service';
import { RaceView } from '../src/features/race/view';
import { SprintSummary } from '../src/features/race/viewer/sprint-panels';
import { timingRows } from '../src/features/race/viewer/model';
import { simulateCareerRace } from '../src/features/race/service';
import { enterNextEvent, isPractice, progressSummary, transitionSession, type CareerProgress } from '../src/game/domain/progression';
import { careerGrid, raceRepository } from './helpers/grid';
import { MemoryQualifyingRepository, sequentialIds } from './helpers/qualifying';
vi.mock('../src/features/career/progression-actions', () => ({ progressionAction: vi.fn() }));
vi.mock('../src/features/practice/actions', () => ({ practiceWeekendAction: vi.fn() }));
vi.mock('../src/features/qualifying/actions', () => ({ qualifyingWeekendAction: vi.fn() }));
vi.mock('../src/features/race/actions', () => ({ raceAction: vi.fn() }));
vi.mock('../src/features/race/viewer/actions', () => ({ viewerAction: vi.fn(), sprintRemainderAction: vi.fn() }));
const html = (node: React.ReactNode) => renderToStaticMarkup(<I18nProvider>{node}</I18nProvider>);
function sprintProgress(progress: CareerProgress) {
    let p = enterNextEvent(progress, progressSummary(progress).next!.id, sequentialIds(700));
    const first = progressSummary(p).active!;
    for (const s of [...first.weekend!.sessions].sort((a, b) => a.order - b.order))
        p = isPractice(s.type) ? transitionSession(p, first.id, s.id, 'simulatePractice') : transitionSession(transitionSession(p, first.id, s.id, 'start'), first.id, s.id, 'completeDevelopment');
    return enterNextEvent(p, progressSummary(p).next!.id, sequentialIds(760));
}
describe('Sprint weekend UI', () => {
    it('the weekend page names the format and offers Manage / Simulate for Sprint Qualifying and the Sprint — never a skip', async () => {
        const g = await careerGrid('team-mclaren');
        let p = sprintProgress(g.progress);
        const event = progressSummary(p).active!, [p1, sq, sprint] = [...event.weekend!.sessions].sort((a, b) => a.order - b.order);
        let text = html(<WeekendView progress={p} eventId={event.id}/>);
        expect(text).toContain('Sprint Weekend');
        for (const label of ['Practice 1', 'Sprint Qualifying', '>Sprint<', 'Qualifying', 'Race']) expect(text).toContain(label);
        expect(text).not.toContain('Practice 2');
        expect(text).not.toContain('Practice 3');
        p = transitionSession(p, event.id, p1.id, 'simulatePractice');
        text = html(<WeekendView progress={p} eventId={event.id}/>);
        expect(text).toContain(`href="/career/${g.career.id}/events/${event.id}/sprint-qualifying"`);
        expect(text).toContain('Manage Sprint Qualifying');
        expect(text).toContain('Simulate Sprint Qualifying (auto-manage)');
        expect(text).toContain('name="kind" value="SPRINT_QUALIFYING"');
        p = transitionSession(transitionSession(p, event.id, sq.id, 'start'), event.id, sq.id, 'completeDevelopment');
        text = html(<WeekendView progress={p} eventId={event.id}/>);
        expect(text).toContain(`href="/career/${g.career.id}/events/${event.id}/sprint"`);
        expect(text).toContain('Manage Sprint');
        expect(text).toContain('Simulate Sprint');
        expect(text).toContain('name="kind" value="SPRINT"');
        expect(text).not.toMatch(/value="skip/i);
        void sprint;
    });
    it('a Standard weekend shows no Sprint sessions or controls', async () => {
        const g = await careerGrid('team-mclaren');
        const p = enterNextEvent(g.progress, progressSummary(g.progress).next!.id, sequentialIds());
        const text = html(<WeekendView progress={p} eventId={progressSummary(p).active!.id}/>);
        expect(text).toContain('Standard Weekend');
        expect(text).not.toContain('<strong>Sprint Qualifying</strong>');
        expect(text).not.toContain('<strong>Sprint</strong>');
        expect(text).not.toContain('/sprint');
        expect(text).not.toContain('Manage Sprint');
        expect(text).toContain('Practice 3');
    });
    it('Sprint Qualifying reads SQ1/SQ2/SQ3 and leads to the Sprint grid; the result table has P1–P22', async () => {
        const g = await careerGrid('team-aurora');
        let p = sprintProgress(g.progress);
        const event = progressSummary(p).active!, p1 = [...event.weekend!.sessions].sort((a, b) => a.order - b.order)[0];
        p = transitionSession(p, event.id, p1.id, 'simulatePractice');
        const repo = new MemoryQualifyingRepository(p, g.roster);
        repo.kind = 'SPRINT_QUALIFYING';
        const view = qualifyingView(await simulateQualifyingSession(repo, g.career.id, event.id));
        const summary = html(<QualifyingSummary view={view}/>);
        expect(summary).toContain('Sprint Qualifying result — Sprint Grid');
        for (const label of ['>SQ1<', '>SQ2<', '>SQ3<']) expect(summary).toContain(label);
        expect(summary).toContain(`href="/career/${g.career.id}/events/${event.id}/sprint"`);
        expect(summary).toContain('Continue to Sprint');
        expect(summary.match(/scope="row"/g)).toHaveLength(22);
        const tower = html(<QualifyingTower view={view} selected={view.entrants[0].entrantId} onSelect={() => {}}/>);
        expect(tower).toContain('Sprint Qualifying classification');
    });
    it('Sprint page: Manage / Simulate Sprint with the Sprint distance; the Sprint Result lists P1–P22 and continues to Qualifying', async () => {
        const g = await careerGrid('team-aurora'), m = raceRepository(g, null, { kind: 'SPRINT', eventIndex: 1 });
        const prep = html(<RaceView data={m.get()}/>);
        expect(prep).toContain('Manage Sprint');
        expect(prep).toContain('Simulate Sprint');
        expect(prep).toContain('Sprint distance');
        expect(prep).toContain('name="kind" value="SPRINT"');
        expect(prep).not.toContain('Start Race');
        await simulateCareerRace(m.repository, g.career.id, m.eventId);
        const data = m.get(), summary = html(<SprintSummary data={data} rows={timingRows(data)}/>);
        expect(summary).toContain('Sprint Result');
        expect(summary).not.toContain('Grand Prix result');
        expect(summary.match(/scope="row"/g)).toHaveLength(22);
        expect(summary).toContain(`href="/career/${g.career.id}/events/${m.eventId}/qualifying"`);
        expect(summary).toContain('Continue to Qualifying');
        expect(summary).toMatch(/class="[^"]*player-row/);
    });
});
