import { describe, it, expect } from 'vitest';
import { prepareVisualSpeed } from '../src/features/race/viewer/speed-profile';
import { RaceMotion } from '../src/features/race/viewer/motion';
import { MarkerPacks, trackClose, badgeText, MAX_LATERAL_OFFSET, densityMode, badgeFootprint, responsiveBadgeScale, type PackCar } from '../src/features/race/viewer/marker-packs';
import { prepareCircuitPath, circuitProjection } from '../src/game/domain/circuit-geometry';
import { circuitLayouts } from '../src/data/seed/circuit-layouts';
const layout = Object.values(circuitLayouts).find(l=>l.id==='monza')!;
const profile = prepareVisualSpeed(prepareCircuitPath(layout));
const target = (a:number,b:number,retired=false) => [{id:'a',progress:a,retired},{id:'b',progress:b,retired:false}];
describe('geometry visual time',()=>{
    it.each(Object.values(circuitLayouts))('$id has positive bounded periodic deterministic time and exact inverse',l=>{
        const p=prepareVisualSpeed(prepareCircuitPath(l));
        expect(p.cumulative).toEqual(prepareVisualSpeed(prepareCircuitPath(l)).cumulative);
        p.velocities.forEach(v=>{expect(v).toBeGreaterThan(.4);expect(v).toBeLessThanOrEqual(1);});
        for(let i=1;i<p.cumulative.length;i++) expect(p.cumulative[i]).toBeGreaterThan(p.cumulative[i-1]);
        for(const x of [-2.1,-.002,0,.99,1,1.002,25.7]) {expect(p.progress(p.time(x))).toBeCloseTo(x,10);expect(p.time(x+1)-p.time(x)).toBeCloseTo(1,10);}
    });
    it('a long straight is meaningfully faster than a tight corner independent of vertex density',()=>{
        const p=prepareVisualSpeed(prepareCircuitPath({...layout,startFinishProgress:0,points:[{x:0,y:0},{x:1,y:0},{x:1,y:.1},{x:0,y:.1}]}));
        expect(p.velocities[100]).toBeGreaterThan(p.velocities[0]*1.3);
    });
    it('arbitrary checkpoint distances stay monotonic, ordered, bounded and reach exact endpoints',()=>{
        for(const delta of [.001,.17,1,3.4]) {
            const m=new RaceMotion(target(.995,.98),0,{green:profile,neutral:profile});m.reconcile(target(.995+delta,.98+delta),1);m.configure('playing',1000);
            let previous=.995;
            for(let t=0;t<=1000;t+=10){m.frame(t);expect(m.progress('a')).toBeGreaterThanOrEqual(previous);expect(m.progress('a')).toBeGreaterThan(m.progress('b'));previous=m.progress('a');}
            expect(m.progress('a')).toBe(.995+delta);
        }
    });
    it('a committed pass crosses once; no extra crossings are generated by curvature',()=>{
        const m=new RaceMotion(target(.4,.39),0,{green:profile,neutral:profile});m.reconcile(target(1.38,1.4),1);m.configure('playing',1000);
        let crossed=false;
        for(let t=0;t<=1000;t+=10){m.frame(t);if(m.progress('b')>m.progress('a')) crossed=true;if(crossed) expect(m.progress('b')).toBeGreaterThan(m.progress('a'));}
        expect(crossed).toBe(true);
    });
    it('launch, pause, speed change, checkpoint replacement, retirement and reduced motion remain continuous',()=>{
        const m=new RaceMotion(target(0,-.01),0,{green:profile,neutral:profile});m.reconcile(target(1,.99),1);m.configure('playing',1000);m.frame(0);m.frame(10);
        expect(m.progress('a')).toBeLessThan(profile.progress(.01));
        const p=m.progress('a');m.configure('paused',250);m.frame(10000);expect(m.progress('a')).toBe(p);
        m.configure('playing',125);m.frame(20000);expect(m.progress('a')).toBe(p);m.frame(20010);expect(m.progress('a')).toBeGreaterThan(p);
        const frozen=m.progress('a');m.reconcile(target(2,1.99,true),2);m.configure('settle',100,true);m.frame(30000);expect(m.progress('a')).toBe(frozen);expect(m.progress('b')).toBe(1.99);
    });
});
const cars=(n:number):PackCar[]=>Array.from({length:n},(_,i)=>({id:`c${String(i).padStart(2,'0')}`,progress:.5,x:500,y:325,nx:0,ny:1,tier:i}));
describe('local marker packs',()=>{
    it.each([2,3,5,8,22])('%i cars stay within a compact envelope without changing progress',n=>{
        const input=cars(n),before=structuredClone(input),m=new MarkerPacks();
        const a=m.frame(input,3000,16),b=m.frame([...input].reverse(),3000,16);
        expect([...a]).toEqual([...b]); expect(input).toEqual(before);
        expect(a.size).toBe(n);
        for(const [id,p] of a){
            expect(Math.abs(p.offset)).toBeLessThanOrEqual(MAX_LATERAL_OFFSET);
            expect(Math.abs(p.target)).toBeLessThanOrEqual(MAX_LATERAL_OFFSET);
            expect(Math.hypot(p.x-500,p.y-325)).toBeLessThanOrEqual(MAX_LATERAL_OFFSET+.001);
            expect(id).toMatch(/^c/);
        }
        if(n===22){
            expect(new Set([...a.values()].map(v=>v.target)).size).toBeLessThan(n); // controlled overlap, no 22-lane fan
            expect(a.get('c00')!.footprint).toBe(1);
            expect(a.get('c01')!.footprint).toBe(.96);
            expect(a.get('c03')!.footprint).toBe(.74);
            expect(a.get('c00')!.density).toBe('DENSE');
        }
    });
    it('selected and teammate retain footprint priority while lower AI compact',()=>{
        const input=cars(22); input[1].tier=1;input[2].tier=2;
        const out=new MarkerPacks().frame(input,3000,16);
        expect(out.get('c00')!.footprint).toBe(1);
        expect(out.get('c01')!.footprint).toBe(.96);
        expect(out.get('c02')!.footprint).toBe(.94);
        expect(out.get('c03')!.footprint).toBe(.74);
        expect([...out.values()].every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y))).toBe(true);
    });
    it('legacy out-of-bound lane memory is clamped on the very next frame',()=>{
        const m=new MarkerPacks();
        (m as unknown as {memory:Map<string,unknown>}).memory.set('c00',{offset:180,target:180,quiet:0,x:500,y:505,footprint:1,density:'NORMAL'});
        const p=m.frame(cars(2),3000,16).get('c00')!;
        expect(Math.abs(p.offset)).toBeLessThanOrEqual(MAX_LATERAL_OFFSET);
        expect(Math.abs(p.target)).toBeLessThanOrEqual(MAX_LATERAL_OFFSET);
        expect(Math.hypot(p.x-500,p.y-325)).toBeLessThanOrEqual(MAX_LATERAL_OFFSET);
    });
    it('responsive and density footprints avoid narrow-screen growth',()=>{
        expect(responsiveBadgeScale(1366)).toBe(1);
        expect(responsiveBadgeScale(768)).toBe(1);
        expect(responsiveBadgeScale(576)).toBeLessThanOrEqual(1.08);
        expect(densityMode(22)).toBe('DENSE');expect(densityMode(7)).toBe('COMPACT');expect(densityMode(2)).toBe('NORMAL');
        expect(badgeFootprint('DENSE',5)).toBeLessThan(badgeFootprint('NORMAL',5));
        expect(badgeFootprint('DENSE',0)).toBe(1);
    });
    it('hairpin and parallel branches never repel on XY alone; start/finish wrap and lapped cars work',()=>{
        const pair=cars(2);pair[1].progress=.7;const m=new MarkerPacks();expect([...m.frame(pair,3000,16).values()].map(v=>v.target)).toEqual([0,0]);
        expect(trackClose(2.995,3.002,3000)).toBe(true);expect(trackClose(.995,2.002,3000)).toBe(true);
    });
    it('real Suzuka crossover branches remain separate',()=>{
        const l=Object.values(circuitLayouts).find(x=>x.id==='suzuka')!,p=prepareCircuitPath(l),project=circuitProjection(l.points);
        let best={d:Infinity,a:0,b:0};
        for(let i=0;i<512;i++)for(let j=i+60;j<512;j++){if(j-i>452)continue;const a=project(p.sample(i/512)),b=project(p.sample(j/512)),d=Math.hypot(a.x-b.x,a.y-b.y);if(d<best.d)best={d,a:i/512,b:j/512};}
        expect(best.d).toBeLessThan(10);expect(trackClose(best.a,best.b,3000)).toBe(false);
        const pair=cars(2).map((c,i)=>({...c,progress:i?best.b:best.a,...project(p.sample(i?best.b:best.a))}));
        expect([...new MarkerPacks().frame(pair,3000,16).values()].map(v=>v.target)).toEqual([0,0]);
    });
    it('offsets return smoothly, freeze while paused and retired positions remain fixed',()=>{
        const m=new MarkerPacks(),pair=cars(2),a=m.frame(pair,3000,16);
        expect(Math.abs(a.get('c01')!.offset)).toBeGreaterThan(0);
        pair[1].progress=.7;
        for(let i=0;i<22;i++)m.frame(pair,3000,16);
        const b=m.frame(pair,3000,16);
        expect(Math.abs(b.get('c01')!.offset)).toBeLessThan(Math.abs(a.get('c01')!.offset));
        expect(m.frame(pair,3000,0).get('c01')!.offset).toBe(b.get('c01')!.offset);
        for(let i=0;i<60;i++)m.frame(pair,3000,16);
        expect(m.frame(pair,3000,16).get('c01')!.offset).toBe(0);
        pair[1].retired=true; const frozen=m.frame(pair,3000,16).get('c01')!;
        pair[1].progress=.8; expect(m.frame(pair,3000,16).get('c01')!.x).toBe(frozen.x);
    });
    it('start/finish text remains secondary to bounded car locations',()=>{
        const input=cars(22), reserved=[{x:470,y:310,w:80,h:30}];
        const out=new MarkerPacks().frame(input,3000,16,false,1,reserved);
        expect([...out.values()].every(p=>Math.abs(p.offset)<=MAX_LATERAL_OFFSET)).toBe(true);
        expect(input.every(c=>c.progress===.5)).toBe(true);
    });
    it('contrasting text works on light and dark fills',()=>{expect(badgeText('#ffffff')).toBe('#101010');expect(badgeText('#000000')).toBe('#ffffff');});
});
