import React from 'react';
import {afterEach,describe,it,expect,vi} from 'vitest';
import {renderToStaticMarkup} from 'react-dom/server';
import {wrapProgress,pointAtProgress,validLayout,interpolateProgress,timingRows,strategicEvent} from '../src/features/race/viewer/model';
import {layoutForCircuit} from '../src/data/seed/circuit-layouts';
import {PlaybackController} from '../src/features/race/viewer/playback';
import {TrackMap} from '../src/features/race/viewer/track-map';
import {DriverPanel} from '../src/features/race/viewer/driver-panel';
import {I18nProvider} from '../src/i18n/provider';
import {translate} from '../src/i18n/catalog';
import {advanceRace,advanceRaceLap} from '../src/simulation/race/engine';
import {quietRace,neutralise,forceMechanical} from './helpers/incidents';
import {modes} from './helpers/commands';
import {viewerData} from './helpers/viewer';
import type {RaceSimulationState} from '../src/simulation/race/types';
afterEach(()=>vi.useRealTimers());
describe('viewer coordinates and classification',()=>{
 it.each(['00000000-0000-4000-8000-000000000300','00000000-0000-4000-8000-000000000301',null])('valid immutable layout %s',id=>{const l=layoutForCircuit(id),before=structuredClone(l);expect(validLayout(l)).toBe(true);expect(pointAtProgress(l,0)).toEqual(pointAtProgress(l,1));expect(pointAtProgress(l,-.25)).toEqual(pointAtProgress(l,4.75));expect(l).toEqual(before);});
 it('rejects invalid and degenerate coordinates',()=>{const l=layoutForCircuit();expect(validLayout({...l,points:[{x:NaN,y:0}]})).toBe(false);expect(()=>pointAtProgress({...l,points:Array(3).fill({x:0,y:0})},0)).toThrow();});
 it('wraps negative, lapped and nonfinite progress',()=>{expect(wrapProgress(-.25)).toBe(.75);expect(wrapProgress(8.25)).toBe(.25);expect(wrapProgress(Infinity)).toBe(0);});
 it('follows absolute progress across finish without extrapolation and freezes retirement',()=>{expect(interpolateProgress(.9,1.1,.5)).toBe(1);expect(interpolateProgress(.9,1.1,2)).toBe(1.1);expect(interpolateProgress(.9,1.1,.5,true)).toBe(1.1);});
 it('preserves authoritative order after passes and never invents overtakes from pit transitions',()=>{const d=viewerData(),before=structuredClone(d);const changed={...d,state:{...d.state!,lap:1,entrants:[...d.state!.entrants].reverse()}};expect(timingRows(changed).map(r=>r.id)).toEqual(changed.state.entrants.map(e=>e.entrantId));timingRows(d);expect(d).toEqual(before);expect(timingRows(d)[0].progress).toBe(d.state!.entrants[0].track!.progressMicrolaps/1e6);});
 it('renaming never changes layout or timing coordinates',()=>{const d=viewerData(),changed={...d,labels:d.labels.map(e=>({...e,driverName:'Edited',teamName:'Renamed'}))};expect(timingRows(changed).map(e=>e.progress)).toEqual(timingRows(d).map(e=>e.progress));expect(layoutForCircuit(changed.circuit.sourceCircuitId)).toBe(layoutForCircuit(d.circuit.sourceCircuitId));});
 it('supports legacy state without track, tyres or commands',()=>{const d=viewerData(),s=d.state!;const legacy={...d,state:{...s,entrants:s.entrants.map(e=>({...e,track:undefined,stint:undefined,pit:undefined,commands:undefined,incident:undefined}))}};expect(timingRows(legacy).every(r=>Number.isFinite(r.progress))).toBe(true);});
 it('renders 20 labelled keyboard-accessible SVG markers and read-only AI controls',()=>{const d=viewerData(20),rows=timingRows(d);const start=performance.now();const markup=renderToStaticMarkup(<I18nProvider><TrackMap layout={layoutForCircuit()} rows={rows} selected={rows[0].id} onSelect={()=>{}} speed={8} reduceMotion={true}/></I18nProvider>);expect(markup.match(/data-car=/g)).toHaveLength(20);expect(markup.match(/tabindex="0"/g)).toHaveLength(20);const ai={...rows[2],player:false};const panel=renderToStaticMarkup(<I18nProvider><DriverPanel data={d} row={ai} busy={false} send={()=>{}}/></I18nProvider>);expect(panel).not.toContain('<button');console.info(`20-car SVG render: ${(performance.now()-start).toFixed(2)}ms, ${markup.length} bytes`);});
 it('finished driver panel removes commands',()=>{const initial=viewerData();const d={...initial,state:advanceRace(initial.state!,1000)};const row=timingRows(d)[0];expect(renderToStaticMarkup(<I18nProvider><DriverPanel data={d} row={row} busy={false} send={()=>{}}/></I18nProvider>)).not.toContain('<button');});
});
describe('sequential checkpoint playback',()=>{
 it('1x and 8x produce exactly equal state for the same command schedule and either locale',async()=>{vi.useFakeTimers();async function run(speed:1|8,locale:'en'|'zh-TW'){let persisted=quietRace();const c=new PlaybackController(persisted,persisted.input.entrants[0].teamId,async s=>{translate(locale,'viewer.lap');persisted=advanceRaceLap(s.lap===8?modes(s,{paceMode:'PUSH',fuelMode:'CONSERVE',ersMode:'DEPLOY'}):s);return structuredClone(persisted);});c.setAutoPause(false);c.setSpeed(speed);c.play();await vi.runAllTimersAsync();expect(c.getSnapshot().playing).toBe(false);expect(persisted.status).toBe('FINISHED');return persisted;}expect(await run(1,'en')).toEqual(await run(8,'zh-TW'));});
 it('pause at lap20 and waiting/rerendering changes no state',async()=>{vi.useFakeTimers();const s=advanceRace(quietRace(),20),advance=vi.fn(async(s:RaceSimulationState)=>advanceRaceLap(s)),c=new PlaybackController(s,s.input.entrants[0].teamId,advance);c.play();c.pause();await vi.advanceTimersByTimeAsync(600000);c.getSnapshot();expect(c.getState()).toEqual(s);expect(advance).not.toHaveBeenCalled();});
 it('rapid play/pause/play/speed changes never overlap requests',async()=>{vi.useFakeTimers();const s=quietRace();let finish!:(s:RaceSimulationState)=>void;const advance=vi.fn(()=>new Promise<RaceSimulationState>(resolve=>finish=resolve));const c=new PlaybackController(s,s.input.entrants[0].teamId,advance);c.play();await vi.advanceTimersByTimeAsync(2400);c.pause();c.play();c.setSpeed(8);await vi.advanceTimersByTimeAsync(20000);expect(advance).toHaveBeenCalledTimes(1);c.pause();finish(advanceRaceLap(s));await vi.advanceTimersByTimeAsync(10000);expect(advance).toHaveBeenCalledTimes(1);});
 it.each(['VSC','SAFETY_CAR'] as const)('auto-pauses at %s with no extra queued lap',async mode=>{vi.useFakeTimers();const s=quietRace(),advance=vi.fn(async(s:RaceSimulationState)=>neutralise(advanceRaceLap(s),mode)),c=new PlaybackController(s,s.input.entrants[0].teamId,advance);c.setSpeed(8);c.play();await vi.runAllTimersAsync();expect(advance).toHaveBeenCalledTimes(1);expect(c.getSnapshot().reason).toBe('CONTROL');});
 it('skip stops at a strategic event even when optional auto pause is off',async()=>{vi.useFakeTimers();const s=quietRace(),advance=vi.fn(async(s:RaceSimulationState)=>({...advanceRaceLap(s),weather:{...s.weather!,rainfallIntensity:900}})),c=new PlaybackController(s,s.input.entrants[0].teamId,advance);c.setAutoPause(false);c.skip();await vi.runAllTimersAsync();expect(advance).toHaveBeenCalledTimes(1);expect(c.getSnapshot().reason).toBe('WEATHER');});
 it('quiet skip is bounded to20 committed laps',async()=>{vi.useFakeTimers();const s=quietRace(),c=new PlaybackController(s,s.input.entrants[0].teamId,async s=>advanceRaceLap(s));c.skip();await vi.runAllTimersAsync();expect(c.getState().lap).toBe(20);expect(c.getSnapshot().reason).toBe('LIMIT');});
 it('a command cancels scheduled playback and never races an advance',async()=>{vi.useFakeTimers();const s=quietRace(),advance=vi.fn(async(s:RaceSimulationState)=>advanceRaceLap(s)),c=new PlaybackController(s,s.input.entrants[0].teamId,advance);c.play();await c.command(async s=>modes(s,{paceMode:'ATTACK'}));await vi.runAllTimersAsync();expect(advance).not.toHaveBeenCalled();expect(c.getState().entrants[0].commands!.paceMode).toBe('ATTACK');});
 it('detects player retirement and finish from authoritative events',()=>{const s=forceMechanical(quietRace(),true),next=advanceRaceLap(s);expect(['CONTROL','RETIREMENT']).toContain(strategicEvent(s,next,s.input.entrants[0].teamId));expect(strategicEvent(s,advanceRace(s,1000),s.input.entrants[0].teamId)).toBe('FINISH');});
});

vi.mock('../src/features/race/viewer/actions',()=>({viewerAction:vi.fn()}));
import {RaceOperations} from '../src/features/race/viewer/operations';
it('renders a complete 20-car timing tower and map without advancing simulation',()=>{const d=viewerData(20),before=structuredClone(d);const started=performance.now();const html=renderToStaticMarkup(<I18nProvider><RaceOperations initialData={d}/></I18nProvider>);expect(html.match(/scope="row"/g)).toHaveLength(20);expect(html.match(/data-car=/g)).toHaveLength(20);expect(d).toEqual(before);console.info(`20-car full viewer SSR: ${(performance.now()-started).toFixed(2)}ms, ${html.length} bytes`);});
it.each(['INCIDENT','RETIREMENT'] as const)('auto-pauses on player %s with no extra lap',async type=>{vi.useFakeTimers();const s=quietRace(),team=s.input.entrants[0].teamId;const advance=vi.fn(async()=>({...s,lap:1,incidents:{...s.incidents!,events:[{sequence:1,lap:1,type,entrantIds:[s.entrants[0].entrantId],kind:'SPIN' as const,severity:'MINOR' as const,timeLossMs:1000}]}}));const c=new PlaybackController(s,team,advance);c.play();await vi.runAllTimersAsync();expect(advance).toHaveBeenCalledTimes(1);expect(c.getSnapshot().reason).toBe(type);});
it('ignores AI incidents and detects actual player pit history growth',()=>{const s=quietRace(),id=s.entrants[0].entrantId,team=s.input.entrants[0].teamId;const ai=s.input.entrants.find(e=>e.teamId!==team)!;expect(strategicEvent(s,{...s,incidents:{...s.incidents!,events:[{sequence:1,lap:1,type:'INCIDENT',entrantIds:[ai.entrantId],kind:'SPIN',severity:'MINOR',timeLossMs:1000}]}},team)).toBeNull();const withRequest={...s,entrants:s.entrants.map(e=>e.entrantId===id?{...e,pit:{...e.pit!,pendingCompound:'HARD' as const}}:e)};expect(strategicEvent(withRequest,advanceRaceLap(withRequest),team)).toBe('PIT');});
it('retired map progress freezes across subsequent authoritative checkpoints',()=>{const retired=advanceRaceLap(forceMechanical(quietRace(),true)),later=advanceRace(retired,5);expect(later.entrants.map(e=>e.track!.progressMicrolaps)).toEqual(retired.entrants.map(e=>e.track!.progressMicrolaps));});

import {createRace} from '../src/simulation/race/engine';
it.each([1,2,3,4,5,6])('renders legacy v%i without fabricated unsupported commands',version=>{const d=viewerData(),input=d.state!.input;const state=createRace({...input,incidents:undefined,weather:version>=6?input.weather:undefined,commands:version>=5?input.commands:undefined,pits:version>=4?input.pits:undefined,interaction:version>=3?input.interaction:undefined,tyres:version>=2?input.tyres:undefined,entrants:input.entrants.map(e=>({...e,startingTyre:version>=2?e.startingTyre:undefined,interaction:version>=3?e.interaction:undefined,strategyController:version>=4?e.strategyController:undefined,reliability:undefined}))});expect(state.simulationVersion).toBe(version);const html=renderToStaticMarkup(<I18nProvider><RaceOperations initialData={{...d,state}}/></I18nProvider>);expect(html).toContain('data-car=');if(version<5)expect(html).not.toContain('>Attack</button>');if(version<4)expect(html).not.toContain('>Box this lap');if(version<2)expect(html).not.toContain('<th>Tyre</th>');});
