"use client";
import Link from 'next/link';
import { useState, useMemo, useEffect, useSyncExternalStore } from 'react';
import { useI18n, LocalizedPageTitle } from '../../../i18n/provider';
import type { CareerRaceData } from '../../../game/domain/race-repository';
import { formatRaceGap, formatRaceTime } from '../../../i18n/race-time';
import { layoutForCircuit } from '../../../data/seed/circuit-layouts';
import { timingRows } from './model';
import { PlaybackController, PLAYBACK_SPEEDS } from './playback';
import { viewerAction } from './actions';
import type { ViewerIntent } from './intents';
import { TrackMap } from './track-map';
import { DriverPanel } from './driver-panel';
import { WeatherPanel } from '../weather-panel';
export function RaceOperations({ initialData }: {
    initialData: CareerRaceData;
}) {
    const { t, format, locale } = useI18n();
    const [data, setData] = useState(initialData);
    const [controller] = useState(() => new PlaybackController(initialData.state!, initialData.progress.career.playerTeamId, async (state) => { const result = await viewerAction(initialData.progress.career.id, initialData.eventId, state.lap, { kind: 'advance' }); if (!result.data)
        throw new Error(result.error!); setData(result.data); return result.data.state!; }));
    const playback = useSyncExternalStore(controller.subscribe, controller.getSnapshot, controller.getSnapshot);
    useEffect(() => () => controller.pause(), [controller]);
    const rows = useMemo(() => timingRows(data), [data]), [selected, setSelected] = useState(() => timingRows(initialData).find(r => r.player)?.id ?? initialData.state!.entrants[0].entrantId), [interval, setIntervalView] = useState(false), [reduceMotion, setReduceMotion] = useState(false);
    const s = data.state!, event = data.progress.events.find(e => e.id === data.eventId)!, row = rows.find(r => r.id === selected) ?? rows[0], layout = layoutForCircuit(data.circuit.sourceCircuitId), control = s.incidents?.mode ?? 'GREEN', weather = s.weather;
    const drsSuspended = control !== 'GREEN' || (s.incidents?.drsDelay ?? 0) > 0 || weather?.drsState === 'DRS_DISABLED_WET';
    const send = (intent: ViewerIntent) => { void controller.command(async (state) => { const result = await viewerAction(data.progress.career.id, data.eventId, state.lap, intent); if (!result.data)
        throw new Error(result.error!); setData(result.data); return result.data.state!; }); };
    const gap = (value: number | null) => value === null ? t('race.lapped') : formatRaceGap(value, locale);
    const events = s.incidents?.events ?? [];
    return <div className="race-ops">
  <LocalizedPageTitle titleKey="viewer.title"/>
  <header className="ops-header"><div><Link className="ops-back" href={`/career/${data.progress.career.id}/events/${data.eventId}`}>← {t('race.back')}</Link><p className="eyebrow">{t('viewer.title')}</p><h1>{event.name}</h1><p className="ops-muted">{event.circuitName}</p></div><div className="race-clock"><span>{t('viewer.lap')}</span><strong>{format.number(s.lap)}<small> / {format.number(s.input.totalLaps)}</small></strong><span className={`control-state control-${control}`}>{t(s.status === 'FINISHED' ? 'incident.FINISHED' : s.incidents ? `incident.${control}` : 'race.running')}</span>{s.incidents && control !== 'GREEN' && s.status !== 'FINISHED' && <small>{t('incident.remaining', { count: format.number(s.incidents.remainingLaps) })}</small>}</div></header>
  <section className="weather-strip" aria-label={t('weather.title')}>{weather ? <><span>{t('weather.rain')} <strong>{format.percentage(weather.rainfallIntensity / 1000, { maximumFractionDigits: 0 })}</strong></span><span>{t('weather.water')} <strong>{format.percentage(weather.trackWater / 1000, { maximumFractionDigits: 0 })}</strong></span><span>{t('weather.air')} <strong>{format.number(weather.airTemperatureMilliC / 1000, { style: 'unit', unit: 'celsius', maximumFractionDigits: 1 })}</strong></span><span>{t('weather.track')} <strong>{format.number(weather.trackTemperatureMilliC / 1000, { style: 'unit', unit: 'celsius', maximumFractionDigits: 1 })}</strong></span></> : <span>{t('viewer.legacy')}</span>}{s.input.interaction && <span className={drsSuspended ? 'drs-off' : 'drs-on'}>{t(drsSuspended ? 'incident.drsSuspended' : 'weather.DRS_ENABLED')}</span>}{(s.incidents?.drsDelay ?? 0) > 0 && <span>{t('incident.restart', { count: format.number(s.incidents!.drsDelay) })}</span>}</section>
  <div className="ops-grid">
   <section className="ops-panel timing-panel" aria-label={t('viewer.timing')}><div className="ops-panel-title"><h2>{t(s.status === 'FINISHED' ? 'race.classification' : 'viewer.timing')}</h2><button className="ops-toggle" onClick={() => setIntervalView(!interval)} aria-pressed={interval}>{t(interval ? 'viewer.interval' : 'viewer.gap')}</button></div>
    <div className="timing-scroll"><table className="timing-tower"><caption className="sr-only">{t(s.status === 'FINISHED' ? 'race.classification' : 'viewer.timing')}</caption><thead><tr><th>{t('race.position')}</th><th>{t('race.driver')}</th><th>{t(interval ? 'viewer.interval' : 'viewer.gap')}</th>{s.input.tyres && <th>{t('viewer.tyre')}</th>}</tr></thead><tbody>{rows.map(r => <tr key={r.id} className={`${r.id === row.id ? 'selected-row' : ''} ${r.status === 'RETIRED' ? 'retired-row' : ''}`}><td>{format.number(r.entrant.position)}<small className="position-change">{r.placesGained ? format.number(r.placesGained, { signDisplay: 'always' }) : '·'}</small></td><th scope="row"><button onClick={() => setSelected(r.id)} aria-pressed={r.id === row.id} className="driver-select" style={{ borderColor: r.color }} title={r.name}><strong>{r.abbreviation}</strong><small>{r.team}</small></button></th><td>{r.status === 'RETIRED' ? t('incident.RETIRED') : r.entrant.position === 1 ? t('race.leader') : gap(interval ? r.interval : r.gap)}<small>{r.pitting ? t('viewer.pit') : r.status === 'FINISHED' ? t('incident.FINISHED') : r.entrant.track?.drsEligible ? t('traffic.drsActive') : r.entrant.pit ? `${t('pit.stops')} ${format.number(r.entrant.pit.stops.length)}` : ''}</small></td>{s.input.tyres && <td>{r.entrant.stint ? <><span className={`tyre-token tyre-${r.entrant.stint.tyre.compound}`} title={t(`tyre.${r.entrant.stint.tyre.compound}`)}>{t(`viewer.tyre.${r.entrant.stint.tyre.compound}`)}</span><small>{t('viewer.age', { count: format.number(r.entrant.stint.tyre.ageLaps) })}</small></> : t('race.noTime')}</td>}</tr>)}</tbody></table></div>
    <p className="tower-note">{t('viewer.positionNote')}</p>
   </section>
   <div className="map-column"><section className="ops-panel track-panel"><div className="ops-panel-title"><h2>{t('viewer.track')}</h2><span className="ops-muted">{t('viewer.schematic')}</span></div><TrackMap layout={layout} rows={rows} selected={row.id} onSelect={setSelected} speed={playback.speed} reduceMotion={reduceMotion || playback.skipping}/><p className="map-notice">{t('viewer.interpolation')}</p><div className="player-switch" role="group" aria-label={t('viewer.playerCars')}>{s.input.entrants.map(e => rows.find(r => r.id === e.entrantId)!).filter(r => r.player).map(r => <button key={r.id} onClick={() => setSelected(r.id)} aria-pressed={r.id === row.id} style={{ borderColor: r.color }}><span>{r.abbreviation} <small>{t('race.position')} {format.number(r.entrant.position)}</small></span><strong>{r.name}</strong><small>{r.entrant.stint ? t(`tyre.${r.entrant.stint.tyre.compound}`) : t('race.noTime')} · {t(`incident.${r.status}`)}</small></button>)}</div></section>
   {weather && <details className="ops-panel forecast-drawer"><summary>{t('weather.forecast')}</summary><WeatherPanel state={s}/></details>}
   <section className="ops-panel events-panel" aria-label={t('viewer.recentEvents')}><div className="ops-panel-title"><h2>{t('viewer.recentEvents')}</h2><span>{format.number(events.length)}</span></div>{events.length === 0 ? <p className="empty-events">{t('incident.empty')}</p> : <ol>{events.slice(-6).reverse().map(e => <li key={e.sequence}><span className="event-lap">{t('incident.lap', { lap: format.number(e.lap) })}</span><div><strong>{t(`incident.${e.type}`)}</strong>{e.kind && <> · {t(`incident.${e.kind}`)}</>}<p>{e.entrantIds.map(id => data.labels.find(l => l.entrantId === id)?.driverName ?? id).join(' · ')}{e.timeLossMs > 0 && <> +{format.number(e.timeLossMs / 1000, { style: 'unit', unit: 'second', maximumFractionDigits: 2 })}</>}</p></div></li>)}</ol>}{events.length > 6 && <details><summary>{t('viewer.allEvents')}</summary><ol>{events.slice(0, -6).map(e => <li key={e.sequence}>{t('incident.lap', { lap: format.number(e.lap) })} · {t(`incident.${e.type}`)} {e.kind && t(`incident.${e.kind}`)} {e.entrantIds.map(id => data.labels.find(l => l.entrantId === id)?.driverName ?? id).join(' · ')}</li>)}</ol></details>}</section>
   </div>
   <DriverPanel key={row.id} data={data} row={row} busy={playback.busy} send={send}/>
  </div>
  <section className="playback-bar" aria-label={t('viewer.playback')}><div className="playback-buttons"><button onClick={playback.playing ? controller.pause : controller.play} disabled={s.status === 'FINISHED'}>{t(playback.playing ? 'viewer.pause' : 'viewer.play')}</button><button className="ops-secondary" onClick={() => void controller.step()} disabled={playback.busy || s.status === 'FINISHED'}>{t('race.lap')}</button><div role="group" aria-label={t('viewer.speed')}>{PLAYBACK_SPEEDS.map(speed => <button className="speed-button" key={speed} onClick={() => controller.setSpeed(speed)} aria-pressed={playback.speed === speed}>{format.number(speed)}×</button>)}</div><button className="ops-secondary" onClick={controller.skip} disabled={playback.busy || s.status === 'FINISHED'}>{t('viewer.nextEvent')}</button></div><div className="viewer-settings"><label><input type="checkbox" checked={playback.autoPause} onChange={e => controller.setAutoPause(e.target.checked)}/>{t('viewer.autoPause')}</label><label><input type="checkbox" checked={reduceMotion} onChange={e => setReduceMotion(e.target.checked)}/>{t('viewer.reduceMotion')}</label><span role="status">{playback.busy ? t('viewer.saving') : playback.playing ? t(playback.skipping ? 'viewer.seeking' : 'viewer.playing') : t(s.status === 'FINISHED' ? 'incident.FINISHED' : 'viewer.paused')}</span></div>{playback.reason && <p role="status">{t(`viewer.reason.${playback.reason}`)}</p>}{playback.error && <p role="alert">{t('viewer.error')}</p>}</section>
  <details className="ops-diagnostics"><summary>{t('viewer.diagnostics')}</summary><p>{t('race.seed')}: {format.number(s.input.seed, { useGrouping: false })} · {t('race.version')}: {format.number(s.simulationVersion)}</p>{rows.map(r => <p key={r.id}>{r.name} · {t('race.total')}: {formatRaceTime(r.entrant.elapsedTimeMs, locale)} · {t('race.best')}: {r.entrant.bestLapTimeMs ? formatRaceTime(r.entrant.bestLapTimeMs, locale) : t('race.noTime')} · {t('traffic.overtakes')}: {format.number(r.entrant.track?.overtakesCompleted ?? 0)}</p>)}</details>
 </div>;
}
